apiVersion: v1
kind: Secret
metadata:
 name: registrypullsecret
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjEyIChkYXJ3aW4pIgoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImV4cGVyaW1lbnRhbCI6ICJkaXNhYmxlZCIsCgkic3RhY2tPcmNoZXN0cmF0b3IiOiAia3ViZXJuZXRlcyIKfQ==
type: kubernetes.io/dockerconfigjson